[supervisord]
nodaemon=true

[program:airupnp]
redirect_stderr=true
command=/bin/airupnp-${BUILD_ARCH} -l 1000:2000
process_name = airupnp-${BUILD_ARCH}

[program:aircast]
redirect_stderr=true
command=/bin/aircast-${BUILD_ARCH}
process_name = aircast-${BUILD_ARCH}

