name: StreamMaster
version: "1.0"
slug: streammaster
description: "Custom addon to run StreamMaster"
startup: services
boot: auto
image: local/streammaster
ports:
  7095/tcp: 7095
map:
  - config:rw
schema: {}
